name: Docker Image CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
	push:
		branches: [ master ]

jobs:
build:
runs-on: ubuntu-latest
	steps:
		- uses: actions/checkout@v1
		- name: Build the Docker image
        run: docker build . --file Dockerfile --tag minimalistic-uploader
        
